data:
  raw_dir: data/raw/Faulty_solar_panel
  processed_dir: data/processed
  train_split: 0.8
  val_split: 0.2

training:
  batch_size: 32
  epochs: 10
  img_height: 224
  img_width: 224
  learning_rate: 0.0005
  model_output: models/solar_model.h5

squiggliness:
  threshold_major: 0.65
  threshold_minor: 0.45
